USE [master]
GO

/****** Object:  Database [CreditCompany]    Script Date: 27/02/2022 21:54:45 ******/
CREATE DATABASE [CreditCompany]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CreditCompany', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CreditCompany.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CreditCompany_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CreditCompany_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CreditCompany].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CreditCompany] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CreditCompany] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CreditCompany] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CreditCompany] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CreditCompany] SET ARITHABORT OFF 
GO

ALTER DATABASE [CreditCompany] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CreditCompany] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CreditCompany] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CreditCompany] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CreditCompany] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CreditCompany] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CreditCompany] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CreditCompany] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CreditCompany] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CreditCompany] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CreditCompany] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CreditCompany] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CreditCompany] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CreditCompany] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CreditCompany] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CreditCompany] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CreditCompany] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CreditCompany] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CreditCompany] SET  MULTI_USER 
GO

ALTER DATABASE [CreditCompany] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CreditCompany] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CreditCompany] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CreditCompany] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CreditCompany] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CreditCompany] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CreditCompany] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CreditCompany] SET  READ_WRITE 
GO


